 services:

  nginx:
    build: nginx
    container_name: pp-nginx
    depends_on:
      - php
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host

  php:
    build: php
    container_name: pp-php
    depends_on:
      - postgres
    volumes:
      - ../project/:/var/www/html/

  redis:
    image: redis
    container_name: pp-redis
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host

  postgres:
    image: postgres:alpine3.15
    container_name: pp-postgres
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    environment:
      POSTGRES_USER: alga
      POSTGRES_PASSWORD: letmein

  adminer:
    image: adminer
    container_name: pp-adminer
    depends_on:
      - postgres
    ports:
      - target: 8080
        published: 8085
        protocol: tcp
        mode: host